# Generated by Django 3.2.5 on 2021-07-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('userpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload_section.userpost')),
                ('file_data', models.FileField(upload_to='')),
            ],
            bases=('upload_section.userpost',),
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('userpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload_section.userpost')),
                ('image_data', models.ImageField(upload_to='')),
            ],
            bases=('upload_section.userpost',),
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('userpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload_section.userpost')),
                ('text_data', models.CharField(max_length=1000)),
            ],
            bases=('upload_section.userpost',),
        ),
    ]
