# Generated by Django 3.2.5 on 2021-07-24 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='FilePost',
            fields=[
                ('userpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload_section.userpost')),
            ],
            bases=('upload_section.userpost',),
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('userpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload_section.userpost')),
                ('image_data', models.ImageField(default='flower-in-desert.jpg', upload_to='images/')),
            ],
            bases=('upload_section.userpost',),
        ),
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('userpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='upload_section.userpost')),
                ('text_data', models.TextField(default='', max_length=2000)),
            ],
            bases=('upload_section.userpost',),
        ),
    ]
